/**
 * posts actions types
 */
export const ActionType = {
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_REQUESTING: "FETCH_POSTS_REQUESTING",
  FETCH_POSTS_ERROR: "FETCH_POSTS_ERROR"
};
